{{- if .Values.global.metric.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "svc.name" . }}
  labels:
    {{- include "svc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "svc.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: gateway
    path: /metrics
    scheme: http
    interval: 5s
{{- end }}