app:
  replicaCount: 1
  port:
    grpc: 8080
    gateway: 80

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

log:
  output: 'std'
  level: debug

image:
  repository: private.naver.com/core
  tag: d93ba
  pullPolicy: Always
